language: objective-c
osx_image: xcode8
cache:
  bundler: true
  cocoapods: true
  directories:
    - ~/.rvm
    - ~/.cocoapods
    - .bundle
    - vendor
env:
  global:
    - WORKSPACE='SwiftUtils.xcworkspace'
    - SCHEME='Framework'
    - SDK='iphonesimulator10.0'
    - DESTINATION='OS=10.0,name=iPhone 6'
install:
  - set -o pipefail
  - brew update
  - ./scripts/setup
  # workaround https://github.com/realm/SwiftLint/issues/13
  - ln -s /Applications/Xcode-8.app /Applications/Xcode.app
script:
  - export REPO_SLUG="$TRAVIS_REPO_SLUG"
  - export SRC_BRANCH="$(./scripts/src_branch)"
  - export PR_NUMBER="$(./scripts/pr_number)"
  - ./scripts/validate_branch
  - ./scripts/lint
  - ./scripts/test
  - ./scripts/pod_test
  - bundle exec pod lib lint --quick
notifications:
  email: false
after_success:
  - ./scripts/codecov
